seed: 23
sellers: 2
bidders: 4
resource-usage: 0.4
distance-limit: 5000
distance-penalty: 8.17
slotsize: 1
end-threshold: 5
min-block: 3
max-block: 3
fairnessPercent: 0.7          #fairness percent and ecopercent should sum up to 1
ecoPercent: 0.3
